App.getDocument('Unnamed').getObject('Sketch').addGeometry(Part.Circle(App.Vector(-97.303635,-94.457016,0),App.Vector(0,0,1),10),True)
>>> App.getDocument('Unnamed').getObject('Sketch').addConstraint(Sketcher.Constraint('Radius',0,10.000000)) 
>>> App.getDocument('Unnamed').getObject('Sketch').addConstraint(Sketcher.Constraint('Equal',0,1)) 
>>> App.getDocument('Unnamed').getObject('Sketch')
>>> conList = []
>>> conList.append(Sketcher.Constraint('InternalAlignment:Sketcher::BSplineControlPoint',0,3,2,0))
>>> conList.append(Sketcher.Constraint('InternalAlignment:Sketcher::BSplineControlPoint',1,3,2,1))
>>> App.getDocument('Unnamed').getObject('Sketch').addConstraint(conList)
>>> 
>>> App.getDocument('Unnamed').getObject('Sketch').exposeInternalGeometry(2)